### ISSUE TITLE
Debugging isn't working on IDEA 14

### ISSUE THREAD

**Issue by lesmo** [nicity/CppTools#7]
It took me a while to get this to work, but I finally did. There's still some work to get done for this to be fine for IDEA 14. It's building wonderfully now.

However, I can't seem to get debugging to work. Every time I hit the _debug_ button, the _debug console_ "freezes" (everything works) not showing anything, nor displaying the process result int (correctly, I assume), but no variables are being watched, and the code doesn't show any pointers as to whether or not it's actually hitting a break-point.

I found an error is being triggered, and here it is:

```
null
java.util.NoSuchElementException
	at java.util.concurrent.LinkedBlockingDeque.removeFirst(LinkedBlockingDeque.java:453)
	at com.advancedtools.cpp.debugger.CppDebugProcess.processOneCommand(CppDebugProcess.java:293)
	at com.advancedtools.cpp.debugger.CppDebugProcess.access$300(CppDebugProcess.java:46)
	at com.advancedtools.cpp.debugger.CppDebugProcess$2.run(CppDebugProcess.java:279)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

I'm not sure if I'm missing a flag for my Makefile, or it's really just the plugin failing here... I'm currently testing with a simple hello-world setup.

**Comment by nicity** [comment]
Hi,
What is your OS? Have you specified path to gdb in the settings?

**Comment by lesmo** [comment]
I was using Ubuntu. I just formatted to Windows because of work, so... yeah. I'm gonna' try to reproduce this in a VM when I find some time.

Can a missing ```gdb``` setting cause it to halt the entire program, and show no output in watchers and the like?
